services:
  mysql:
    image: mysql:8.0
    container_name: mysql_study_smart
    environment:
      MYSQL_DATABASE: study_smart
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
