services:
  postgres:
    image: postgres:latest
    container_name: postgres_study_smart
    environment:
      POSTGRES_DB: study_smart
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - '5439:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: